[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["rm -f package-lock.json", "npm install --no-package-lock"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "npm start"